name: mumble
summary: Mumble is an open source, low-latency, high quality voice chat software. # 79 char long summary
description: |
  Mumble is a voice chat application for groups. While it can be used for any
  kind   of activity, it is primarily intended for gaming. It can be compared
  to programs like Ventrilo or TeamSpeak. People tend to simplify things, so
  when they talk   about Mumble they either talk about "Mumble" the client
  application or about "Mumble & Murmur" the whole voice chat application suite.
adopt-info: mumble

grade: stable
confinement: strict

apps:
  mumble:
    command: desktop-launch $SNAP/bin/mumble
    environment:
      ALSA_CONFIG_PATH: $SNAP/etc/alsa.conf
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - network-manager
      - opengl
      - pulseaudio
      - unity7
      - x11

parts:
  mumble:
    after: [desktop-qt5]
    plugin: qmake
    source: https://github.com/mumble-voip/mumble.git
    source-branch: "master"
    qt-version: qt5
    options:
      - CONFIG+=no-alsa no-oss no-server -recursive no-update packaged no-embed-qt-translations release bundled-celt symbols
    override-build: |
      git submodule init
      git submodule update
      snapcraftctl build
      if [ ! -d $SNAPCRAFT_PART_INSTALL/bin ]; then
        mkdir $SNAPCRAFT_PART_INSTALL/bin
      fi
      cp -R release/* $SNAPCRAFT_PART_INSTALL/bin
      snapcraftctl set-version "$(git describe --tags)"
    build-packages:
      - ice35-slice
      - ice35-translators
      - libavahi-compat-libdnssd-dev
      - libboost1.58-dev
      - libcap-dev
      - libg15daemon-client-dev
      - libgl1-mesa-dev
      - libogg-dev
      - libopus-dev
      - libprotobuf-dev
      - libpulse-dev
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - libsndfile1-dev
      - libspeechd-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libssl-dev
      - libxi-dev
      - libzeroc-ice35-dev
      - protobuf-compiler
      - qt5-default
      - qttools5-dev-tools
    stage-packages:
      - libasyncns0
      - libavahi-compat-libdnssd1
      - libflac8
      - libg15daemon-client1
      - libgl1-mesa-glx
      - libglu1-mesa
      - libgtk2.0-0
      - libogg0
      - libprotobuf9v5
      - libpulse0
      - libqt5sql5-sqlite
      - libqt5xml5
      - libsndfile1
      - libspeechd2
      - libspeex1
      - libspeexdsp1
      - libthai-data
      - libvorbis0a
      - libvorbisenc2

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
